version: "3.9"
services:
  db:
    build:
      context: ./database/
      dockerfile: Dockerfile
    restart: always
    environment:
      MYSQL_DATABASE: "omniflight"
      # So you don't have to use root, but you can if you like
      MYSQL_USER: "user"
      # You can use whatever password you like
      MYSQL_PASSWORD: "password"
      # Password for root access
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - "3306:3306"
    expose:
      # Opens port 3306 on the container
      - "3306"
      # Where our data will be persisted
    volumes:
      - omniflight-db:/var/lib/mysql
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_NAME=omniflight
      - DB_USER=user
      - DB_PASSWORD=password
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true
  # Names our volume
volumes:
  omniflight-db:
